from typing import Protocol

class ObjectStorage(Protocol):
    async def put_object(self, bucket: str, key: str, data: bytes) -> str: ...
    async def get_object(self, bucket: str, key: str) -> bytes: ...
